<html>
	<head>
		<title>Administração</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php
			// Add CSS
			//$this->headLink()->appendStylesheet( $this->BaseUrl() . '/css/960gs/reset.css' );
			//$this->headLink()->appendStylesheet( $this->BaseUrl() . '/css/960gs/text.css' );
			//$this->headLink()->appendStylesheet( $this->BaseUrl() . '/css/960gs/960.css' );
			$this->headLink()->appendStylesheet( $this->BaseUrl() . '/css/backend.css' );
			$this->headLink()->appendStylesheet( $this->BaseUrl() . '/css/uniform.default.css' );
			//$this->headLink()->appendStylesheet( $this->BaseUrl() . '/css/jqtransform.css' );
			
			// Add JS
			$this->headScript()->prependFile( $this->BaseUrl() . '/js/backend.js' );
			//$this->headScript()->prependFile( $this->BaseUrl() . '/js/jquery.jqtransform.js' );
			$this->headScript()->prependFile( $this->BaseUrl() . '/js/jquery.uniform.min.js' );
			$this->headScript()->prependFile( $this->BaseUrl() . '/js/jquery-1.7.1.min.js' );
			
			// Carregando o css e o javascript
			echo $this->headLink() . "\n\n\t\t";
			echo $this->headScript();
		?>
	</head>
	<body>
		<div id="menu">
			<ul id="nav-one" class="nav">
				<li>
					<a href="#">Administrar</a>
					<ul>
						<li><a href="<?php echo $this->BaseUrl(); ?>/group">Listar grupos</a></li>
						<li><a href="<?php echo $this->BaseUrl(); ?>/group/add">Adicionar grupo</a></li>
						<li><a href="<?php echo $this->BaseUrl(); ?>/group/permissions">Permissões de Grupo</a></li>
						<li><a href="<?php echo $this->BaseUrl(); ?>/user">Listar usuários</a></li>
						<li><a href="<?php echo $this->BaseUrl(); ?>/user/add">Adicionar usuário</a></li>
					</ul>
				</li>
			</ul>
		</div>
		
		<div id="content">
			<?php 
				echo $this->layout()->content;
			?>
		</div>
		
		<div id="footer">Desenvolvedor: Diogo Alexsander Cavilha</div>
	</body>
</html>